### ISSUE TITLE
ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by Nobody84** [schinken/ftp2telegram#1]
The app crashes after some minute with the following message:
```
{"name":"ftp-srv","hostname":"42a86518e568","pid":18,"id":"2129be03-ca4f-42ac-bad2-9e3c3375e439","ip":"192.168.25.41","level":50,"msg":"Satisfy Parameters Error { error: 'Socket not writable' }","time":"2021-01-17T11:55:59.834Z","v":0}
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Reproduction steps:**
1. Clone the repository. Last commit: fa7ac8f0792bdc288e84f700af38019a2da61bac
2. Build the docker container. `docker build -t ftp2telegram:latest .`
3. Run the docker container: `docker run --dns 8.8.8.8 -v $(pwd)/config:/usr/src/app/config -v $(pwd)/logs:/root/.npm/_logs -p 9021:21 -p 21000-21010:21000-21010 --rm -it ftp2telegram:latest`

**Environment:**
Intel NUC-Kit N3050 1.6GHz, 4GB Ram, 120GB SSD
Docker version 19.03.14, build 5eb3275d40
4 FTP client (Surviliance Cam, Reolink RLC-410-5MP) connected

**Debug Log**
[2021-01-17T11_56_00_467Z-debug.log](https://github.com/schinken/ftp2telegram/files/5826039/2021-01-17T11_56_00_467Z-debug.log)

**Comment by schinken** [comment]
Hi @Nobody84. Thanks for posting this bug report! 

Do you have an example config file for me? You can of course strip users and passwords ;) I've never tried it with multiple FTP clients though. My dahua camera only connects every time a new image is available once

Does this error happen on idle or when a camera tries to upload something?

**Comment by Nobody84** [comment]
Thanx for your reply.

Here my config:
```
module.exports = {
    ftp: {
        url: 'ftp://0.0.0.0:21',
        pasv: {
            ip: '192.168.25.5',
            portMin: 21000,
            portMax: 21010,
        },
        credentials: {
            'cam': 'xxxFtpPasswordxxx'
        }
    },

    telegram: {
        token: 'xxxApiTokenxxx,
        chatIds: [xxxChatGroupIdxxx]
    }
};
```

Im pretty sure that the cameras are sending data, because I tested the motion detection, but I'm not sure if a cam is transmitting date at the time of the crash. I also don't know if the cams try to open a new connection every time they send an image. 

What I can say is that when I connect to the server using an FTP client and upload multiple images, it semes to work as intended.

**Comment by schinken** [comment]
Thanks for the config! Nothing unusual here ;) 
I'm now thinking what I can do to reproduce and track this error down. Are you familiar with tcpdump/wireshark? Do you think it's possible to capture that error/track your FTP traffic  and see on which command it fails?

Maybe it's some kind of timed out connection.
The JSON-Logged Error defintely comes from ftp-srv
* https://github.com/autovance/ftp-srv/blob/4cd88b129cce47f8f84b75994f9fb326cf5b7703/src/connection.js#L141

But the rejection is catched here...
* https://github.com/autovance/ftp-srv/blob/4cd88b129cce47f8f84b75994f9fb326cf5b7703/src/connection.js#L151

hm... 
"This error originated either by throwing inside of an async function without a catch block"

**Comment by Nobody84** [comment]
Yes I agree. This semes to be an issue for the ftp-srv.

Thanx for helping.

**Comment by schinken** [comment]
@Nobody84 Maybe we can reproduce this and fix the issue in ftp-srv? :)
