### ISSUE TITLE
Multiple Users and defined paths

### ISSUE THREAD

**Issue by pitbullcan** [schinken/ftp2telegram#3]
Hello, I tried the application and it was go. this provides for a sound backup system.
But I think it would be nice if you can add provision for multiple users and users defined paths.
username:password : /path/
username2:password2 : /path2/....

Just my suggestion.

Thanks

**Comment by KonstantinKa** [comment]
Hello friend!
How i can add work path to current dir?

Thanks

**Comment by schinken** [comment]
I'm not sure what you mean. There is no real path. The file only gets uploaded to memory and sent to telegram. There is no local file or directory. ftp2telegram does not care about directories only about the uploaded file

If you need more than one path use more instances of the application with different config
