### ISSUE TITLE
ERR_UNHANDLED_REJECTION while testing

### ISSUE THREAD

**Issue by bbfendt** [schinken/ftp2telegram#4]
Hello there and thx for creating good stuff like this and sharing it with the world ! :)

I was looking for a solution to get videoclips of my surveillance-cameras over to my telegram-chat. Both cams can use FTP and SFTP so your tool seemed to be perfect. I just tried ftp2telegran and ran into a problem. I am quite a noob without much knowledge of how all this stuff works so i better tell you what i did step by step:

- I am running "Dietpi" on a Raspberry 3B+
- Installed Node.js (node --version says v18.0.0) and GIT
- I cloned your Repository ("git clone *url*")
- i went to cd \ftp2telegram
- did "npm install"
- copied config/default.js to config/production.js and edited production.js to fit my needs:

**module.exports = {
    ftp: {
        url: 'ftp://0.0.0.0:21',
        pasv: {
            ip: '192.168.178.52',
            portMin: 21000,
            portMax: 21010,
        },
        credentials: {
            'test': 'test'
        }
    },

    telegram: {
        token: 'my:token',
        chatIds: [-mychatid]
    }
};**

- tried to start it with "npm run start" -> it got me an Telegram-Bot-Error
- found out in the end i had to edit the default.js instead of the the productive.js
- Started again this time sucessful:

**root@Testberry:~/ftp2telegram# npm run start

> ftp2telegram@1.0.0 start
> node index.js

[bot.plugin] loaded 'regExpMessage' plugin
[bot.plugin] loaded 'shortReply' plugin
{"name":"ftp-srv","hostname":"Testberry","pid":12489,"level":30,"protocol":"ftp","ip":"0.0.0.0","port":"21","msg":"Listening","time":"2022-04-28T19:37:27.687Z","v":0}
Server is running
[bot.info] bot started**

- Then i started up WinSCP on my Windows-PC, connected sucessfully to my Testberry-IP with FTP-Protocol using Port 21 and my credentials. WinSCP connected sucessfully and showed me an empty folder ("/")
- Now whenever i try to upload something (.jpg, .mp4, whatever) WinSCP throws an error "conneciton lost" and the TestPi tells me as follows:

**{"name":"ftp-srv","hostname":"MotionEye2k22","pid":12634,"id":"6b476a87-5911-4388-bf7d-ccc0f4f46b0c","ip":"192.168.178.29","directive":"MDTM","level":50,"err":{"message":"File not found","name":"Error","stack":"Error: File not found\n    at MemoryFileSystem.get (/root/ftp2telegram/lib/MemoryFileSystem.js:64:19)\n    at /root/ftp2telegram/node_modules/ftp-srv/src/commands/registration/mdtm.js:10:38\n    at tryCatcher (/root/ftp2telegram/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise.attempt.Promise.try (/root/ftp2telegram/node_modules/bluebird/js/release/method.js:39:29)\n    at FtpConnection.handler (/root/ftp2telegram/node_modules/ftp-srv/src/commands/registration/mdtm.js:10:23)\n    at FtpCommands.handle (/root/ftp2telegram/node_modules/ftp-srv/src/commands/index.js:70:28)\n    at /root/ftp2telegram/node_modules/ftp-srv/src/connection.js:47:67\n    at tryCatcher (/root/ftp2telegram/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.gotValue (/root/ftp2telegram/node_modules/bluebird/js/release/reduce.js:166:18)\n    at Object.gotAccum (/root/ftp2telegram/node_modules/bluebird/js/release/reduce.js:155:25)\n    at Object.tryCatcher (/root/ftp2telegram/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/root/ftp2telegram/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/root/ftp2telegram/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromiseCtx (/root/ftp2telegram/node_modules/bluebird/js/release/promise.js:641:10)\n    at _drainQueueStep (/root/ftp2telegram/node_modules/bluebird/js/release/async.js:97:12)\n    at _drainQueue (/root/ftp2telegram/node_modules/bluebird/js/release/async.js:86:9)"},"msg":"File not found","time":"2022-04-28T19:44:39.669Z","v":0}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.0.0**

What could i be doing wrong ?

Thanks and regards :)

PS: I also speak German if that makes it easier

**Comment by schinken** [comment]
Hi... i tried the same but got a diffrerent error first. Then I tried with a  groupId... and then it worked. 
Did you try it with a "private chat"-id?

I fixed the production/default thingy btw

**Comment by bbfendt** [comment]
Hello and thank you for your fast reply !

I just changed the ChatID I was using for testing purposes into a GroupID as you suggested and that did the Trick. 
Now all works as it's supposed to.

Thanks so much !

Unfortunately I ran into another issue now but i´ll have to do a bit more research on that and perhaps open another thread then...

Best Regards.
