### ISSUE TITLE
couldn't find the uploaded files

### ISSUE THREAD

**Issue by qiangweihewu** [schinken/ftp2telegram#6]
Hi there!
I succeeded to upload one small mp4 format file, but failed to upload all the other formats and even larger mp4 files. Could you help to figure out what's going on? Thanks a lot!
 
Here are the logs:

| {"name":"ftp2telegram","hostname":"baobao","pid":37041,"level":30,"filename":"vtt22srt.py","msg":"Upload started","time":"2022-11-24T15:31:56.256Z","v":0}

0|index    | {"name":"ftp2telegram","hostname":"baobao","pid":37041,"level":30,"filename":"vtt22srt.py","msg":"Upload finished","time":"2022-11-24T15:31:56.635Z","v":0}

0|index    | {"name":"ftp2telegram","hostname":"baobao","pid":37041,"level":50,"filename":"vtt22srt.py","msg":"Can't determine Mime-Type","time":"2022-11-24T15:31:56.636Z","v":0}

0|index    | {"name":"ftp-srv","hostname":"baobao","pid":37041,"id":"6940d1b4-02a5-4a4a-970e-f223843eb886","ip":"111.194.50.101","directive":"MDTM","level":50,"msg":"File \"20211123083300 vtt22srt.py\" **not found.**","time":"2022-11-24T15:31:57.052Z","v":0}

**Comment by schinken** [comment]
Can you try to change this line:
https://github.com/schinken/ftp2telegram/blob/master/lib/TelegramProxy.js#L40

to just `} else {` and see if that solves your problem? If yes, I can patch that.

**Comment by qiangweihewu** [comment]
> Can you try to change this line: https://github.com/schinken/ftp2telegram/blob/master/lib/TelegramProxy.js#L40
> 
> to just `} else {` and see if that solves your problem? If yes, I can patch that.

Thanks! Seems worked btter, but still poped up these issues:

1/ couldn't upload .txt files, logs are:

0|index  | {"name":"ftp2telegram","hostname":"baobao","pid":89208,"level":50,"filename":"gfwlist.txt","msg":"Can't determine Mime-Type","time":"2022-11-26T14:31:49.301Z","v":0}

2/ could upload files probably larger than 100mb

0|index  | {"name":"ftp2telegram","hostname":"baobao","pid":89208,"level":30,"filename":"67-final-2-mp4.mp4","mimeType":"video/mp4","msg":"Sending to telegram","time":"2022-11-26T14:30:06.578Z","v":0}

0|index  | { ok: false, error_code: 413, description: 'Request Entity Too Large' }

Look forward to any suggestions, thanks!

**Comment by schinken** [comment]
> 1/ couldn't upload .txt files, logs are:
> 
> 0|index | {"name":"ftp2telegram","hostname":"baobao","pid":89208,"level":50,"filename":"gfwlist.txt","msg":"**Can't determine Mime-Type**","time":"2022-11-26T14:31:49.301Z","v":0}

That might be fixable. I'll try this weekend and let you know

> 2/ could upload files probably larger than 100mb
> 
> 0|index | {"name":"ftp2telegram","hostname":"baobao","pid":89208,"level":30,"filename":"67-final-2-mp4.mp4","mimeType":"video/mp4","msg":"Sending to telegram","time":"2022-11-26T14:30:06.578Z","v":0}
> 
> 0|index | { ok: false, **error_code: 413, description: 'Request Entity Too Large**' }

This one might not be fixable. Looks like Telegram does not accept a 100MB file.... But I'll also look into it... because I read there might be more possible with the stream api or sth. like that. Just googled like 2 minutes.. I'll let you know if I have something

**Comment by schinken** [comment]
Good news! 

Issue 1 is fixed (get the new version :))
Issue 2 can't be fixed, because **bot's can only upload 50MB**. Only users can upload up to 1.5GB...

**Comment by qiangweihewu** [comment]
> Good news!
> 
> Issue 1 is fixed (get the new version :)) Issue 2 can't be fixed, because **bot's can only upload 50MB**. Only users can upload up to 1.5GB...

Thanks for the work! I will renew it. Meanwhile, I just found a project which seems to make uploading larger files possible by dividing them into small chunks, here it is:
https://github.com/RuslanUC/TelegramFTP.git

Just wonder whether it is possible to merge it.

**Comment by schinken** [comment]
No sadly not. This is using mtproto not the bot-api like my project. To use this you need a separate telegram account etc.
With the bot-api you can use a bot but it's sadly limited
